### ISSUE TITLE
Unable to load pretrained model

### ISSUE THREAD

**Issue by kamalkraj** [brianhuang1019/RL-Chatbot#8]
Use default model

Traceback (most recent call last):
  File "python/test.py", line 138, in <module>
    test()
  File "python/test.py", line 72, in test
    saver.restore(sess, default_model_path)
  File "/home/kamalraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/kamalraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/kamalraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/kamalraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/kamalraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [7634,1000] rhs shape= [6851,1000]
         [[Node: save/Assign_4 = Assign[T=DT_FLOAT, _class=["loc:@Wemb"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Wemb,
save/RestoreV2_4)]]

**Comment by brianhuang1019** [comment]
check your tensorflow version, should be 1.0.*
or re-download the pretrained model

**Comment by lokeshphani123** [comment]
I have tensorflow-1.0.1, But I still see the same issue.  Here, my intention is to train model from scratch.

I see following issue:
![5DD28F29-D637-45ED-A7D2-53A96BA34211](https://user-images.githubusercontent.com/43857311/83727710-812cae80-a613-11ea-930d-5e26c89bc967.jpeg)
